name: Generate Single HTML
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Bundler Script
        run: node build.js

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Single-HTML-Output
          path: dist/index.html
